# Generated by Django 2.0.2 on 2018-08-30 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 18, 51, 13, 935751, tzinfo=utc), verbose_name='fecha de publicacion'),
        ),
    ]
