# Generated by Django 2.0.2 on 2018-09-01 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180901_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 12, 18, 55, 997126, tzinfo=utc), verbose_name='fecha de publicacion'),
        ),
    ]
