# Generated by Django 2.0.2 on 2018-09-01 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180901_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 18, 38, 5, 894676, tzinfo=utc), verbose_name='fecha de publicacion'),
        ),
    ]
