# Generated by Django 2.0.2 on 2018-09-05 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180905_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 13, 48, 11, 797634, tzinfo=utc), verbose_name='fecha de publicacion'),
        ),
    ]
