# Generated by Django 2.0.2 on 2018-09-05 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180905_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 14, 45, 13, 816208, tzinfo=utc), verbose_name='fecha de publicacion'),
        ),
    ]
