# Generated by Django 2.0.2 on 2018-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Nombre Clave')),
                ('name', models.CharField(max_length=200, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
            ],
            options={
                'verbose_name': 'enlaces',
                'ordering': ['name'],
            },
        ),
    ]
